export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const UPDATE_RECIPES = "UPDATE_RECIPES";

// export const QUERY_ALL_RECIPES = "QUERY_ALL_RECIPES";
export const QUERY_RECIPES = "QUERY_RECIPES";
export const QUERY_CATEGORIES = "QUERY_CATEGORIES";
export const QUERY_USER = "QUERY_USER";
export const ADD_RECIPES = "ADD_RECIPES";



    